### ISSUE TITLE
Title Selection Save Editor & Backup/Restore is not working for 0.10.1

### ISSUE THREAD

**Issue by zteioh** [WerWolv/EdiZon#104]
When I try to open one of any titles it just automatically freeze becoming unresponsive, the only thing that currently works at this moment is cheats listing.

**Comment by jpn-tm** [comment]
I can see the same problem after the Atmosphere update.
And after watching the freeze for a while, Atmosphere crashes and ask for Reboot.

**Comment by AnalogMan151** [comment]
Does no one look at the closed issues before opening a new one? Literally the last closed issue: #103

**Comment by mos46072** [comment]
I'm experience this problem, what is full ram mode though? I'm total noob here please help

**Comment by ELY3M** [comment]
I have same issue but I resolved it by running hbmenu with full ram.  
hold R and tap on one of your games to open hbmenu and tap on edizon.
