### ISSUE TITLE
Stopped recognizing JoyCon inputs

### ISSUE THREAD

**Issue by Philipp-94** [WerWolv/EdiZon#110]
So after the latest atmosphere update 0.10.2 the joycons stopped working in edizon 3.0.1 for me. Redownloaded and reinstalled atmosphere and edizon. The nightly works kinda, but doesn't find any editable games. 
Any suggestions what I did wrong?

**Comment by Wolf-poop** [comment]
I'm experiencing the same issue after updating. Edizon loads fine but won't recognize any joycon inputs.

**Comment by WerWolv** [comment]
Please update Edizon to the snapshot version 3.1.0
