### ISSUE TITLE
Don't have a stable release compiled with the latest LibNX

### ISSUE THREAD

**Issue by TheGinGear** [WerWolv/EdiZon#117]
Seriously, just recompile the old stable release or something so that your software works on latest firmware

**Comment by WerWolv** [comment]
Version 3.0.1 is completely broken not only thanks to libnx changes but also because of Firmware and Atmosphere changes. Please use https://github.com/WerWolv/EdiZon/releases/download/snapshot/EdiZon.nro which has been updated to work again more or less.
