### ISSUE TITLE
EdiZon crashes after selecting any title 

### ISSUE THREAD

**Issue by tk1076408** [WerWolv/EdiZon#120]
Firmware 9.1.0 (Atmosphere 0.10.2-master-d5458960)

I tired EdiZon v3.0.1 (https://github.com/WerWolv/EdiZon/releases/tag/v3.0.1), and v3.1.0-nightly (snapshot build https://github.com/WerWolv/EdiZon/releases/snapshot)

For snapshot build I tried with 2 ways: 
1. remove all previous version, and just put downloaded EdiZon.nro to the SD card root folder. 
2. Mix it with v3.0.1 SD files and just replace the EdiZon.nro file with the snapshot build

No luck on either way mentioned above, v3.0.1 don't take joy-con input, and snapshot build just crash when selecting any title. (cuphead and zelda-botw)

Any suggestions?

screenshots:
![IMG_4187](https://user-images.githubusercontent.com/7875150/73328466-bb71e380-420e-11ea-9dbd-d721b1d5faa5.jpg)

**Comment by TechGeekGamer** [comment]
Issue was resolved in the EdiZon Discord server.

**Comment by tk1076408** [comment]
Resolved:  OOM issue due to launching EdiZon through Album.
1.  Hold R and launch a game
2. Open EdiZon
3. Try what you were trying to do
