### ISSUE TITLE
SXOS cheat format support

### ISSUE THREAD

**Issue by Asunix666** [WerWolv/EdiZon#122]
Please add support for cheat format that sxos uses. In edizon cheats don't appear.

**Comment by WerWolv** [comment]
Atmosphere and SX cheats are pretty much identical. Atmosphere supports all cheats that run on SXOS. If cheats don't show up, make sure you're using Atmosphere 0.10.2 and the EdiZon Snapshot 3.1.0

**Comment by Asunix666** [comment]
I have all that. Using Latest Kosmos on 9.1.0. The thing is when playing a game like Spyro, in sxos shows all cheats but in edizon shows just one. Like:
 [600000 gems]
580F0000 0616E400
780F0000 000002C4
640F0000 00000000 000927C0

But not the rest like:

[01# Moonjump]
80000002
580F0000 069CB520
580F1000 00000000
580F1000 00000020
580F1000 00000078
580F1000 00000048
580F1000 00000008
780F0000 000000DC
640F0000 00000000 44000000
20000000

Tested with sxos.

I don't want to use sxos again.

**Comment by WerWolv** [comment]
There must be a error in the cheat file then. Atmosphere validates them a lot more thoroughly than SX plus there are certain limits. First one being, there can't be more than 128 different cheats in there, There can't be more than one Master cheat ( The one in { } brackets ), there can't be more than 1024 opcodes ( each pack of 8 numbers like 580F1000 is one opcode ) and there can't be any characters besides 0-9 and A-F outside of the cheat names ( the text in [ ] brackets ). Make sure that's all valid

**Comment by Asunix666** [comment]
Uhh. Sorry for my lack of experience. I just now found that it copies cheats from "titles" and paste them in "contents" and read them from there. The issue was, it didn't copy all cheats codes from a file. I fixed by pasting all my cheats in "contents". Sorry for bothering you.
