### ISSUE TITLE
No config for this game was found. Editing is disabled.

### ISSUE THREAD

**Issue by steph9009** [WerWolv/EdiZon#125]
From snapshot Edizon release, when i try to edit Dark Souls, Odissey, Zelda, or any game in offline database (https://github.com/WerWolv/EdiZon_CheatsConfigsAndScripts/) i have this message:

"No config for this game was found. Editing is disabled."

But all the editors worked with previous version!

**Comment by Lapin** [comment]
Well at least you could get it working at some point. That msg is the only thing I could get. And if I try to add scripts etc, at some points controllers stop working and the only workaround to reinstall everything again.

**Comment by TechGeekGamer** [comment]
Use the update feature of EdiZon, also please ask questions in the "EdiZon ⚡ Tesla" Discord server in the future. https://discord.gg/qyA38T8

**Comment by steph9009** [comment]
i fixed it myself throwing root/EdiZon folder from SD root to root/switch folder.

**Comment by Wolffel** [comment]
> 
> 
> Use the update feature of EdiZon, also please ask questions in the "EdiZon ⚡ Tesla" Discord server in the future. https://discord.gg/qyA38T8

From atmosphere I can't see the update button of edizon. I think is disabled
