### ISSUE TITLE
Is the edizon work on atmosphere 0.10.4?

### ISSUE THREAD

**Issue by frankyan96** [WerWolv/EdiZon#128]
I recently updated the atmosphere to 0.10.4 My switch is on 9.2.0
Right now I cannot activate the cheat menu anymore. I placed all my cheats in atmosphere/titles. 
I ran the game and went to the edizon, there is no cheat in my cheat menu

**Comment by TechGeekGamer** [comment]
Not an EdiZon issue. All cheats now go in `atmosphere/contents/<titleid>/cheats`

**Comment by frankyan96** [comment]
thank you so much!
