### ISSUE TITLE
Crash when choosing Game in the Edizon App

### ISSUE THREAD

**Issue by lambolyu** [WerWolv/EdiZon#132]
TegraRcmGUI 2.6
hekate ctcaer 5.1.3
Firmware 9.2.0
Atmosphère 0.10.5
EdiZon snapshot
SD 64GB FAT32

When I select the game app, and push OK (button A), the app don't show my player list but  go freezing about 20 seconds, then shows the Error number of Atmosphère: 0x1003 (2003-0008).

Is that issue of EdiZon or I should go Atmosphère to post this one? Thanks a lot.

**Comment by TechGeekGamer** [comment]
Try running from a game instead. (Hold R while launching a game from the HOME menu, then launch EdiZon)

**Comment by lambolyu** [comment]
Shows "The save files of a running game cannot be accessed."

I guess that might be my "player select list" problem?

**Comment by TechGeekGamer** [comment]
Do you have any sysmodules running?

**Comment by lambolyu** [comment]
I actually download the SD cards form AtlasNX/Kosmos, but I am sure I choose no "Sys Modules".

I can do the "batch backup" in app-selecting menu of EdiZon, and it works, but cannot enter the app.

**Comment by TechGeekGamer** [comment]
Would it be ok continuing to help you in the "EdiZon ⚡ Tesla" Discord server? https://discord.gg/qyA38T8

**Comment by lambolyu** [comment]
OK.

**Comment by lambolyu** [comment]
Problem fixed. Bur dont know why.

According to people form Discord, I hold R while launching another game from the HOME menu, then launch EdiZon to select my game and succeed to entering.
