### ISSUE TITLE
Button presses not working

### ISSUE THREAD

**Issue by rmilejcz** [WerWolv/EdiZon#135]
Just did a fresh hack on a newly acquired Switch. I currently only have one game (Diablo III). I am able to launch EdiZon and I see Diablo III but no inputs are registered when pressing buttons. I can only press the home button to leave EdiZon.

I don't have "HBG" (I don't think I do, I followed this guide to get my CFW running: https://nh-server.github.io/switch-guide/) and this Atmosphere install is 100% fresh.

**Comment by TechGeekGamer** [comment]
Switch to the nightly/snapshot version.

**Comment by TechGeekGamer** [comment]
https://github.com/WerWolv/EdiZon/releases/tag/snapshot

**Comment by rmilejcz** [comment]
Thanks, I'll try it!

**Comment by TechGeekGamer** [comment]
@rmilejcz Did it work?

**Comment by rmilejcz** [comment]
Hey sorry, yes it did
