### ISSUE TITLE
opening cheats menu crashes AMS

### ISSUE THREAD

**Issue by Cantiel** [WerWolv/EdiZon#145]
i'm sorry if this is the correct place, or if i should have posted this on the tesla site

whenever i open the edizon cheat list in through the tesla overlay in story of seasons: FOMT, atmosphere crashes and i have to restart the system. i tried to use the edizon version linked in the grandia thread (since it's a similar problem, but that doesn't work either)

**Comment by ioistired** [comment]
Confirmed in ACNH 1.3.1

**Comment by DanielC7205** [comment]
The EdiZon app doesn’t support Animal Crossing. This is a known issue. You should use the Tesla overlay instead.

**Comment by Conan179** [comment]
i can confirmed, tesla OVERLAY working with acnh 1.3.1.

**Comment by ioistired** [comment]
Oh, the Tesla overlay doesn't work for me either with ACNH 1.3.1. It crashes AMS as well.

**Comment by Conan179** [comment]
bad cheat file

**Comment by ELY3M** [comment]
about crashing ams with tesla overlay.
it happens to me if I have too many cheats in txt file.
I had to reduce the cheats in txt

**Comment by ioistired** [comment]
That's pretty gay ngl

**Comment by WerWolv** [comment]
You're welcome I guess
