### ISSUE TITLE
Trouble with Xenoblade 2 

### ISSUE THREAD

**Issue by grannybrown** [WerWolv/EdiZon#154]
Hi,
I’m not very experienced with these programs. I used a rcm injector to insert the updated version of atmosphere and Edizon and have them up and running, but I need some help.
I tried using some cheats from the master list and I haven’t been able to get any of the cheats to work. I’m wondering if I did some setup wrong. The path I have the folder in is athmosphere - contents- title ID —cheats 
In addition, 
What is a good way to correct the “Cheats for this game present but title version or region doesn't match.”

**Comment by Masamune3210** [comment]
That error means that cheats were found but are either for a different version of the game or for a different region. Cheats will only work with the update and region of the title they were made for

**Comment by grannybrown** [comment]
Hey that actually helped me realize I made a silly  mistake. Cheats work !

**Comment by Masamune3210** [comment]
It happens lol, I don't know how many times I've just simply overlooked something that ended up being the issue. Glad you got it working!
