### ISSUE TITLE
Unable to enter a range of values for "A..B" search mode

### ISSUE THREAD

**Issue by flarn2006** [WerWolv/EdiZon#155]
It says I'm supposed to enter two values, but when I do, it just puts the first one in the text box and ignores the second one. It gives me a keypad where I can enter the digits 0-9, as well as the characters `-` and `.`, so I tried entering both `13-16` and `13..16`, and in both cases it just said "13" in the text box. I even tried using hexadecimal mode since that provides a full keyboard, in case there was an oversight and it expects a character I can't type. I tried separating it with a space, a colon, and a comma; neither of those worked.

Google gives me multiple threads in which someone has asked for help using this mode, but unfortunately none of them have received an answer. Looking at the source code, my best guess is that the range entry code is simply missing.

**Comment by littlesten** [comment]
Glad I'm not the only one.

**Comment by masagrator** [comment]
> Glad I'm not the only one.

Move to Edizon-SE, dawg

**Comment by littlesten** [comment]
> > Glad I'm not the only one.
> 
> Move to Edizon-SE, dawg

Edizon SE crashes for me so I'm on the latest snap shot build. Any older versions of SE crashes after 2 or 3 searches.

**Comment by WerWolv** [comment]
The reason the `A..B` mode doesn't work is because I never implemented it.
