### ISSUE TITLE
Edizon dmnt:cht problem, please help

### ISSUE THREAD

**Issue by RALazuardi** [WerWolv/EdiZon#169]
Edizon depends on Atmosphere's dmnt:cht service which seem to be running on this device. Please install a supported CFW to use the cheat engine

:(

**Comment by lookye** [comment]
Use atmosphere cfw. If you do so, please seek help e.g. on discord (its linked in the readme directly under the edizon logo). Github issues are for for bugs and is no a support forum.

**Comment by RALazuardi** [comment]
i use atmosphere already, version 0.18.1 on 11.0.1 firmware

**Comment by RALazuardi** [comment]
Helo?
