### ISSUE TITLE
Crash and cheats don't work

### ISSUE THREAD

**Issue by Scruffy803** [WerWolv/EdiZon#175]
I was using cheats on Pokemon sword, just having fun offline, and my switch crashes, I boot it up again and then it says no cheats loaded while it was working just fine earlier just tested it and with other games it loads

**Comment by masagrator** [comment]
Edizon is outdated. Use Edizon-SE

https://github.com/tomvita/EdiZon-SE

**Comment by Scruffy803** [comment]
> Edizon is outdated. Use Edizon-SE
> 
> https://github.com/tomvita/EdiZon-SE

Ohhhh, I was using edizon se I didn't know they were different things. Thx will post my issue rhere

**Comment by lookye** [comment]
Then please close this issue here.

**Comment by SpooderMaan803** [comment]
Wrong edizon
