### ISSUE TITLE
 My account was hijacked, so I sent spam and was banned from the discord server Please return

### ISSUE THREAD

**Issue by yyoossk** [WerWolv/EdiZon#177]
My account was hijacked, so I sent spam and was banned from the discord server
Please return

**Comment by yyoossk** [comment]
I am Japanese
I saw the content of the spam, but I have no benefit at all
Innocent and victim

**Comment by yyoossk** [comment]
https://twitter.com/Cloud0835/status/1471056708860772358

**Comment by WerWolv** [comment]
I unbanned you. If anything else happens, please DM me on Discord

**Comment by yyoossk** [comment]
thank you so much!
