### ISSUE TITLE
Wrong first start warning

### ISSUE THREAD

**Issue by lookye** [WerWolv/EdiZon#41]
**Describe the bug**
I am using ReiNX 2.0 and at the first start of EdiZon 2.2.0 the red warning message says I am using SX OS. I never used SX OS and never will.

**To Reproduce**
Just use ReiNX 2.0 and a fresh version of the latest EdiZon.

**Expected behavior**
The red warning message will pop up and says I am using a cfw I never used.

**Screenshots**
![2019020616522600-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/45557556/52338167-f1202a00-2a09-11e9-8020-1ac8fcc63f5d.jpg)

**Additional context**
---

**Comment by WerWolv** [comment]
That's an issue with ReiNX right now. You can just dismiss it.
I implemented a check for ReiNX because they added the tx service which I use to detect SX OS. It will be fixed once Rei releases an update
