### ISSUE TITLE
transfer.sh incomplete upload

### ISSUE THREAD

**Issue by zkitX** [WerWolv/EdiZon#42]
**Describe the bug**
When downloading an uploaded file from transfer.sh the save files are missing from the uploaded tar, It only includes `edizon_save_metadata.json`

**To Reproduce**
1. Select any game
2. Backup the save
3. Press Restore, hover over the name of the backup, press minus to upload
4. Download uploaded file
5. only contains  `edizon_save_metadata.json`

**Expected behavior**
Uploads entire backup

**Comment by WerWolv** [comment]
Uhm. That really shouldn't happen. What games did you try this on?

**Comment by zkitX** [comment]
Seems to be an issue with savegames located in subfolders

**Comment by WerWolv** [comment]
Thanks! Going to fix that as soon as I can :)

**Comment by WerWolv** [comment]
Fixed in release v3.0.0
