### ISSUE TITLE
windows has no sys/socket.h

### ISSUE THREAD

**Issue by d3st1nyh4x** [WerWolv/EdiZon#44]
windows missing dependency
#include <sys/socket.h>

**To Reproduce**
build on windows

**Expected behavior**
windows is a POS and does not have some libraries

**Additional context**
no biggie just pointing it out for any noob users that cant build and wana try out your sweet sweet edizon cheat stuff

**Comment by WerWolv** [comment]
You've most likely not downloaded all dependencies from devkitpro's pacman. I'm building edizon on both Windows 10 and Antergos (Arch Linux) with no issues

**Comment by d3st1nyh4x** [comment]
you are right a fresh install of devkitpro and dependencies builds with no issues
