### ISSUE TITLE
Cheats are disabled by default

### ISSUE THREAD

**Issue by rashevskyv** [WerWolv/EdiZon#47]
**Is your feature request related to a problem? Please describe.**
Please make cheats disabled by default. For now I need to change override in atmosphere settings for disabling cheats by default.

**Describe the solution you'd like**
It would be very comfortable if I can play with working cheat engine and ram editor, but without cheats that I did not activate by myself

I saw it this way - I launch the game without cheats by first time and if I need cheat to be apply - I launch EdiZon and choose anly what I need.

**Comment by WerWolv** [comment]
I talked to SciresM about that as well and his reason was that the cheat engine should also be useable without EdiZon per se so he added a config option.
It's easy enough to quickly change the system_settings.ini option though so I don't think this is really an issue.

I don't like just bundling a modified config with edizon tbh.

**Comment by rashevskyv** [comment]
Maybe you just can make all chits didabled in edizon? All checkboxes off or something

**Comment by WerWolv** [comment]
Changing the value in the config is easy enough. Also Kosmos now ships with it being disabled by default

**Comment by Smoker1** [comment]
Unfortunately, this is still a problem, but with a new twist - Updating to the latest Atmosphere, the system_settings.ini you need to Edit is in the

sd:/atmosphere/config
or
sd:/atmosphere/config_templates

But I had to get a Linked Account, and now, no matter what I do, they are ALWAYS on! I can't even hold L to turn them Off anymore

**Comment by TechGeekGamer** [comment]
@Smoker1 Make sure the edited `system_settings.ini` is in `atmosphere/config`.
