### ISSUE TITLE
hope support disable assembly cheat code

### ISSUE THREAD

**Issue by xspeedfly** [WerWolv/EdiZon#48]
assembly cheat code can not disable after enable,hope edizon can support disable assembly code

for example
[Cheat1]
04000000 12345678 11111111
#04000000 12345678 00000000

enable will use no # line
disable will use all # line

thanks for you read it

**Comment by WerWolv** [comment]
That's no issue regarding edizon. Atmosphere's dmnt:cht handles all the cheat codes so you should open an issue over there
