### ISSUE TITLE
build id

### ISSUE THREAD

**Issue by novalkun** [WerWolv/EdiZon#49]
i'd like to know if edizon can show the build id for every game started

**Comment by EnterpriseFreak** [comment]
Yeah that would be really helpful. According to switchbrew (https://switchbrew.org/wiki/NSO) the build id is located in the main NSO of the game at the offset 0x40 and has a size of 0x20 bytes. Just to help speed up things a bit :)

**Comment by WerWolv** [comment]
Was implemented in https://github.com/WerWolv/EdiZon/commit/c86e65aada600a029a9b826167c6e113285fb719
