### ISSUE TITLE
Graphical overlap in cheat list

### ISSUE THREAD

**Issue by AnalogMan151** [WerWolv/EdiZon#51]
**Describe the bug**
When more than 8 cheats are in the cheat list, the "And X more..." text is overlapped by the inside of a non-existent check box blocking out part of the "A".

**To Reproduce**
Load a game for which you have more than 8 cheats for. Make sure cheats are disabled by default in Atmosphere configuration settings. Load EdiZon through an applet and enter Cheats screen. View the cheat list and observe the text "And X more..."

**Expected behavior**
When cheats quantity is greater than 8 that the inside of the eighth checkbox is not drawn.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/18319133/54075593-291bc680-426f-11e9-9699-aa80342ee2a4.jpg)

**Additional context**
NA

**Comment by WerWolv** [comment]
Noticed that today as well. Thanks! Fixing it asap
