### ISSUE TITLE
Can't control the buttons on the transfer.sh dialog with buttons

### ISSUE THREAD

**Issue by EnterpriseFreak** [WerWolv/EdiZon#56]
**Describe the bug**
You can't activate any option on the dialog wich asks if you want to upload the savegame to trashfer.sh with the A button.

**To Reproduce**
Backup any save and wait for the dialog wich asks if you want to upload the save to transfer.sh then try to activate yes or no with the A button.

**Expected behavior**
Ability to activate the yes or no option with the A button.

**Comment by WerWolv** [comment]
Just tested. Selecting the `Yes` option with A works. No somehow doesn't. What a weird bug. Fixing it!

**Comment by EnterpriseFreak** [comment]
Even more interesting the No option does work with the B button.

**Comment by WerWolv** [comment]
B just closes the message box no matter what. I probably just didn't implement the No option properly
