### ISSUE TITLE
Deleting backups doesn't update list

### ISSUE THREAD

**Issue by ckurtz22** [WerWolv/EdiZon#57]
**Describe the bug**
When I delete a backup with X it doesn't disappear from list until I leave the "restore" menu and reopen it

**To Reproduce**
Select game > Y (Restore) > X (Delete)

**Expected behavior**
Deleting a backup should remove it from the list automatically

**Comment by WerWolv** [comment]
Rip. I managed to break quite a few things by being lazy lately. Working on it
