### ISSUE TITLE
Switch Freezes

### ISSUE THREAD

**Issue by leesinoflee** [WerWolv/EdiZon#61]
**Describe the bug**
Whenever I press Y (Search Ram), the Switch locks up and freezes and would only respond by holding down the power button to restart into RCM and injecting a payload once again.
**To Reproduce**
Enter Edizon with a game in the background, press Y for cheats, and press Y again to search ram causing a freeze.
**Expected behavior**
Press Y to search RAM for values.

**Comment by Vercalos** [comment]
Question; does this happen with every game on your Switch, or only one so far?

I've not had this issue before. The only trouble I have had was when I was running ReiNX, which doesn't have the same built-in RAM cheat support as the Atmosphere/Kosmos CFW.

**Comment by Brawl345** [comment]
Do you have any custom sysmodules active? Same happens for me if I have at least three sys modules activated (sys-ftpd + sys-clk + ldn_mitm) and perform a RAM search. Seems like the console is hitting its memory limit. Happens with every keyboard widget (try pressing HOME while in game and going to the internet settings for example and editing the name -> console freezes the same way).

**Comment by leesinoflee** [comment]
Oh yeah, I do have freebird active, but it's not exactly turned on. Not sure if I have any others, but it would seem to be just freebird and sys-ftpd.

**Comment by Brawl345** [comment]
Try the latest version of Atmosphère, it fixed the problem for me.
