### ISSUE TITLE
[compile]compile error KeyboardManager.cpp

### ISSUE THREAD

**Issue by zsword** [WerWolv/EdiZon#64]
Compile error:
../EdiZon/source/KeyboardManager.cpp:142:29: error: 'FASTSCROLL_WAIT' was not declared in this scope
         svcSleepThread((u64)FASTSCROLL_WAIT);
../EdiZon/source/KeyboardManager.cpp:315:20: error: 'gfxGetFramebuffer' was not declared in this scope
         framebuf = gfxGetFramebuffer(&framebuf_width, NULL);
...

**Comment by WerWolv** [comment]
Uhh you got a really really old version of Edizon apparently or something went wrong during pulling the new changes. The keyboard manager was a test ages ago that was never finished and discarded again pretty quick
