### ISSUE TITLE
Compile Error -> error: cannot convert 'std::vector<unsigned char>' to 'u8*' {aka 'unsigned char*'} in return

### ISSUE THREAD

**Issue by nabel0** [WerWolv/EdiZon#65]
C:/Users/maniac/Documents/Development/EdiZon/source/helpers/title.cpp: In constructor 'Title::Title(FsSaveDataInfo&)':
C:/Users/maniac/Documents/Development/EdiZon/source/helpers/title.cpp:76:10: error: cannot convert 'std::vector<unsigned char>' to 'void*'
   memcpy(m_titleIcon, ptr, imagesize);
          ^~~~~~~~~~~
In file included from c:\devkitpro\devkita64\aarch64-none-elf\include\c++\8.3.0\cstring:42,
                 from C:/Users/maniac/Documents/Development/EdiZon/include/helpers/save.hpp:3,
                 from C:/Users/maniac/Documents/Development/EdiZon/include/helpers/title.hpp:9,
                 from C:/Users/maniac/Documents/Development/EdiZon/source/helpers/title.cpp:1:
c:\devkitpro\devkita64\aarch64-none-elf\include\string.h:31:17: note:   initializing argument 1 of 'void* memcpy(void*, const void*, size_t)'
 void *  memcpy (void *__restrict, const void *__restrict, size_t);
                 ^~~~~~
C:/Users/maniac/Documents/Development/EdiZon/source/helpers/title.cpp: In member function 'u8* Title::getTitleIcon()':
C:/Users/maniac/Documents/Development/EdiZon/source/helpers/title.cpp:99:10: error: cannot convert 'std::vector<unsigned char>' to 'u8*' {aka 'unsigned char*'} in return
   return m_titleIcon;
          ^~~~~~~~~~~
make[1]: *** [/c/devkitPro/devkitA64/base_rules:14: title.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:165: build] Error 2

**Comment by WerWolv** [comment]
That's an error caused because I was stupid and pushed something I wasn't yet supposed to. I'm rewriting the memory dump class right now so once that one's done and working I'll push all my changes and this should be fixed. Sorry for that
