### ISSUE TITLE
Edizon erasing /switch folder

### ISSUE THREAD

**Issue by es0501** [WerWolv/EdiZon#68]
I've found a weird bug that occurs when searching ram.

When I do a search, go to the game, then go to head back to Edizon my /switch folder will have been completely emptied, nothing else on the sdcard is touched just the files in /switch.

**Comment by WerWolv** [comment]
Guess you're using an exFAT card? When using homebrew that accesses the SD card it's very likely for them to corrupt and that's exactly what happens then. Format your SD card to FAT32 and try again. Won't happen again then

**Comment by es0501** [comment]
Thank you it's just weird that it only erases that one folder.

**Comment by WerWolv** [comment]
It's because EdiZon exclusively accesses data in the /switch folder so part of your SD card corrupted and the rest is still going to be fine. But if you're using an exFAT card with any homebrew really that accesses the SD card you're playing with fire anyways
