### ISSUE TITLE
Unable to View PROPER Build ID

### ISSUE THREAD

**Issue by Smoker1** [WerWolv/EdiZon#75]
When Viewing Cheats (or none showing), it does not show the Actual Build ID of the Game.

Also, not sure what happened, but Cheats for NSMBU-D was working and showing up, but then, it stopped showing up. Same Game, same Cheat File, but now it wont come up. Tried using the latest Nightly which did not have Cheat Function in it, I went back to using the latest Build with Cheats, and now it will not come up

**Comment by WerWolv** [comment]
That's a Atmosphere 0.9.2 issue. There has been a shadow update that fixes it. Redownload 0.9.2 and it should work again
