### ISSUE TITLE
Attached controllers doesn't work

### ISSUE THREAD

**Issue by zxcvnnvcxz** [WerWolv/EdiZon#79]
Atmosphere version 9.0.4
emuMMC Firmware 9.0.0
Hekate 5.0.2

Latest version of edizon, touchscreen and home button works, but no other buttons on the joycons work.

**Comment by WerWolv** [comment]
Update Atmosphere but this time properly. Atmosphere's hid-mitm isn't running on your system.
I'll update Edizon properly once I have time
