### ISSUE TITLE
can't use controller

### ISSUE THREAD

**Issue by riouhunter** [WerWolv/EdiZon#87]
hi, i'm using nintendo switch 9.0.1|AMS 0.9.4|S
hbmenu v3.1.1
nx-hbloader v2.2.0
and edizon 3.1.0 nighly

i can't use controller on edizon but the touchscreen is fine.
can't  activate or deactive cheat using touchscreen.

Can you help me?

**Comment by donys999** [comment]
it will randomly work for just a moment and then stop for me i havent been able to update edizon at all without using a controller

**Comment by WerWolv** [comment]
Stop using Tinfoil/HBG, clean your SD card and install Atmosphere or Kosmos from scratch again.
