### ISSUE TITLE
joycons wont work only the home button

### ISSUE THREAD

**Issue by kbetsu** [WerWolv/EdiZon#93]
ATMOSPHERE 0.9.4
when I open the app I can only use the touch screen, joycons only work to press the home button to exit can u help me with this? also are u guys going to add full touch screen support? so theres no need to use the joycons 

note: also not working in some other apps but in hbappstore and hbgshop working fine only not working in edizon and emuiibo

**Comment by WerWolv** [comment]
Stop using hbg and reinstall atmosphere
