### ISSUE TITLE
Possible Atmosphere 10.0 issues?

### ISSUE THREAD

**Issue by DanielC-08** [WerWolv/EdiZon#97]
Since Atmosphere changes folders, wouldn’t that cause issues?

**Comment by vanpome** [comment]
I tried out atmosphere 10.0 -> EdiZon now has issues. Can't active cheat anymore.  Any possible update soon guys? Or do you have any alternative tools other than EdiZon

**Comment by eien-mb** [comment]
Same issue here, seems EdiZon is still looking into the old 'titles' folder(?).

**Comment by AnalogMan151** [comment]
Possibly update this line here and test?
https://github.com/WerWolv/EdiZon/blob/4c1a86cedb7d35116b525876bef9ece93c907b37/source/update_manager.cpp#L246

**Comment by vanpome** [comment]
@AnalogMan151  wow that was fast I hope WerWolv update the app soon

**Comment by HookedBehemoth** [comment]
It's updated on master

**Comment by dirron93** [comment]
okay I'm Going to sound stupid here but I'm new. how do i make the source code into a working app with the updated directories could someone point me to a tutorial or do you have an updated verison of edizon the routes to the content folder?

**Comment by DanielC-08** [comment]
@dirron93 
Do you have Discord? I can talk with you there.

**Comment by dirron93** [comment]
@DanielC-08 picklez93 is my discord

**Comment by DanielC-08** [comment]
@dirron93 what is the ending tag?

**Comment by dirron93** [comment]
Picklez93#4192 @DanielC-08

**Comment by juzzash** [comment]
> Possibly update these lines here and test?
> 
> https://github.com/WerWolv/EdiZon/blob/4c1a86cedb7d35116b525876bef9ece93c907b37/source/update_manager.cpp#L246
> 
> 
> https://github.com/WerWolv/EdiZon/blob/8c63b1258b3603a15180faf1c921966b51cf9231/source/guis/gui_cheats.cpp#L1431

@AnalogMan151 i located the source files and how to make the edits you suggested. But how do we take all the source files and turn it into an .NRO file to drop onto my st card for atmosphere?

**Comment by DanielC-08** [comment]
This issue was fixed in the latest snapshot.
